name = "SquareDanceReasoning"
uuid = "b9c7be03-8993-4d9d-899b-7f8d1d493d3a"
authors = ["MarkNahabedian <naha@mit.edu> and contributors"]
version = "1.0.0-DEV"

[deps]
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Rete = "3d46c559-9b3d-4aba-9ca1-48ff7627231e"
XML = "72c71f33-b9b6-44de-8c94-c961784809e2"

[compat]
OrderedCollections = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
